### ISSUE TITLE
App crashs at start

### ISSUE THREAD

**Issue by pylapp** [michaelnisi/podest#40] opened 2021-12-29 16:30 UTC
Using an iPhone 12 Pro under iOS 15.1.1 with french language, Wifi connection and no VPN nor blockers, when I start the last version of Podest (version 10.0), the application crashes.

I don't see any UI displayed ; the app crashes freshly after tapped on the app icon.

@michaelnisi I sent by email the crash report picked from my device.

**Comment by michaelnisi** [comment] 2021-12-29 18:27
@pylapp Thank you very much for your feedback, Pierre-Yves 💜 I will look into that. 

Do you mind sending me the Crash Log? 

- Settings > Privacy > Analytics & Improvements > Analytics Data
- Search for Podest
- Select Log Item
- ⬆️ Share via Email or Copy-Paste here ⬇️

I‘m sorry for your inconvenience and hope I we can resolve this issue soon.

**Comment by pylapp** [comment] 2021-12-29 18:52
I sent you by email the report this afternoon ; feel free to send by an email If you don't get it :)

**Comment by michaelnisi** [comment] 2021-12-30 11:09
I have no idea yet but here we go, **10.1** 🔜 https://testflight.apple.com/join/NCebqL7A

**Comment by pylapp** [comment] 2021-12-31 13:20
Feel free to contact me to get more detail ; console.app traces have been sent and my _sydiagnose_ is ready :-)

**Comment by michaelnisi** [comment] 2021-12-31 17:43
Thank you, @pylapp Would you mind trying [10.1 (2)](https://testflight.apple.com/join/NCebqL7A)? Let me know if the issue is still around 🧪

**Comment by pylapp** [comment] 2021-12-31 22:38
﻿And… it works!

I get back my podcast feeds 😍

You are awesome !

I am glad to see you can improve so quickly the app with user feedback, it’s very nice!



—
Pierre-Yves Lapersonne (a.k.a pylapp)
pylapersonne.info



—
Pierre-Yves Lapersonne
pylapersonne.info

**Comment by michaelnisi** [comment] 2022-01-01 16:23
Resolved with 10.1 🚀 Thank you, @pylapp

**Closed by michaelnisi** 2022-01-01 16:23 UTC
Labels: bug, 10.1
